INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Friends');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Family');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Enemys');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Some');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('G');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('H');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('J');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('K');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('L');

INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`, `mail`) VALUES ('Alecey', 'gfdfg', 'qqq@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`) VALUES ('Dmitryi', 'ffgv');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `skype`, `mail`) VALUES ('Xenya', '12312312312', 'bhhg', 'www@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `skype`, `mail`) VALUES ('Vladimir', '12342342343', 'ikh', 'eee@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('A');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `mail`) VALUES ('B', '45676543456', 'rrr@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`, `mail`) VALUES ('C', 'hj', 'ttt@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`) VALUES ('D', '87678765676');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive1');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive2');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive3');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive4');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive5');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive6');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive7');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive8');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive9');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Unactive0');

INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('1', '1');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('1', '2');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('1', '3');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('2', '4');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('2', '5');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('2', '6');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('3', '1');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('3', '4');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('3', '7');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('4', '2');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('4', '6');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('4', '8');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('5', '1');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('5', '2');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('5', '4');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('6', '3');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('6', '6');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('6', '9');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('7', '4');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('7', '7');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('8', '1');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('8', '6');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('9', '4');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('9', '5');
INSERT INTO `handbook_schema`.`link_table` (`group_id`, `contact_id`) VALUES ('9', '7');
