INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('not group');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Friends');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Family');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Enemys');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('Some');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('G');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('H');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('J');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('K');
INSERT INTO `handbook_schema`.`group_table` (`group_name`) VALUES ('L');

INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`, `mail`) VALUES ('Alecey', 'gfdfg', 'qqq@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`) VALUES ('Dmitryi', 'ffgv');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `skype`, `mail`) VALUES ('Xenya', '12312312312', 'bhhg', 'www@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `skype`, `mail`) VALUES ('Vladimir', '12342342343', 'ikh', 'eee@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('A');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`, `mail`) VALUES ('B', '45676543456', 'rrr@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `skype`, `mail`) VALUES ('C', 'hj', 'ttt@mail');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`, `phone`) VALUES ('D', '87678765676');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some1');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some2');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some3');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some4');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some5');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some6');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some7');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some8');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some9');
INSERT INTO `handbook_schema`.`contact_table` (`contact_name`) VALUES ('Some0');

INSERT INTO `handbook_schema`.`user_table` (`user_name`) VALUES ('RU');
INSERT INTO `handbook_schema`.`user_table` (`user_name`) VALUES ('US');
INSERT INTO `handbook_schema`.`user_table` (`user_name`) VALUES ('JP');
INSERT INTO `handbook_schema`.`user_table` (`user_name`) VALUES ('CA');

INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '3', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '4', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '5', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '6', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '1', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '4', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '7', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('4', '6', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('4', '8', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('5', '1', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '2', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('5', '4', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('6', '3', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('6', '6', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('6', '9', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('7', '4', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('7', '7', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('8', '1', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('8', '6', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('9', '4', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('9', '5', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('10', '7', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('11', '8', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('12', '8', '1');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('14', '9', '1');

INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '1', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '3', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '5', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '7', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '9', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '6', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('4', '4', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('5', '7', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('7', '5', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('9', '2', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('12', '2', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('15', '3', '2');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('16', '3', '2');

INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('10', '2', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '4', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('2', '5', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '7', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('1', '9', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('4', '6', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('5', '4', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('5', '7', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('6', '5', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('6', '2', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('8', '2', '3');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('11', '2', '3');

INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '2', '4');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '4', '4');
INSERT INTO `handbook_schema`.`link_table` (`contact_id`, `group_id`, `user_id`) VALUES ('3', '5', '4');